### ISSUE TITLE
ATtiny25v vs ATtiny25

### ISSUE THREAD

**Issue by thilbig** [azya52/carrera#4]
Hi there,
could it be that the ATtiny25 does not work like the ATtiny25v? I'm having timing issues when using an ATtiny25. Everything works perfectly with the ATtiny25v.

Sincerely yours,

Thomas

**Comment by thilbig** [comment]
I was able to solve the problem.

**Comment by criptomillon2025** [comment]
hi im working with attiny25v but dosent work colud you help pls? thanks
